// EMB3D: Component Specification & Pin Mapping Database

const ComponentDatabase = {
    arduino_uno: {
        id: 'arduino_uno',
        name: 'Arduino Uno R3',
        category: 'mcu',
        tag: 'Microcontroller',
        description: 'The classic 8-bit AVR development board. Utilizes the ATmega328P microcontroller, operating at 16 MHz with 32 KB flash memory. Ideal for prototyping low-power peripheral interfaces.',
        specs: {
            'Microcontroller': 'ATmega328P',
            'Operating Voltage': '5V',
            'Input Voltage (Recommended)': '7-12V',
            'Digital I/O Pins': '14 (of which 6 provide PWM output)',
            'Analog Input Pins': '6',
            'DC Current per I/O Pin': '20 mA',
            'Flash Memory': '32 KB (ATmega328P) of which 0.5 KB used by bootloader',
            'SRAM': '2 KB',
            'EEPROM': '1 KB',
            'Clock Speed': '16 MHz'
        },
        customizer: [
            { name: 'PCB Color', type: 'color', default: '#00539C', options: ['#00539C', '#101216', '#1E4620', '#C0392B'] },
            { name: 'Header Styling', type: 'select', default: 'Female Socket', options: ['Female Socket', 'Male Header', 'None'] }
        ],
        pins: [
            { num: 1, name: 'D0 / RX', type: 'comm', desc: 'Digital Pin 0; Hardware Serial Receiver (UART RX). Pulled high by default.' },
            { num: 2, name: 'D1 / TX', type: 'comm', desc: 'Digital Pin 1; Hardware Serial Transmitter (UART TX). Synchronous UART transmit line.' },
            { num: 3, name: 'D2', type: 'digital', desc: 'Digital General Purpose Input/Output Pin 2. Supports External Interrupt 0.' },
            { num: 4, name: 'D3 / PWM', type: 'pwm', desc: 'Digital I/O Pin 3. Renders 8-bit Phase-Correct/Fast Pulse Width Modulated signals.' },
            { num: 5, name: 'D4', type: 'digital', desc: 'Digital I/O Pin 4. General digital pin.' },
            { num: 6, name: 'D5 / PWM', type: 'pwm', desc: 'Digital I/O Pin 5. Renders PWM logic signals.' },
            { num: 7, name: 'D6 / PWM', type: 'pwm', desc: 'Digital I/O Pin 6. Renders PWM logic signals.' },
            { num: 8, name: 'D7', type: 'digital', desc: 'Digital I/O Pin 7. General digital pin.' },
            { num: 9, name: 'D8', type: 'digital', desc: 'Digital I/O Pin 8. General digital pin.' },
            { num: 10, name: 'D9 / PWM', type: 'pwm', desc: 'Digital I/O Pin 9. Renders PWM logic signals.' },
            { num: 11, name: 'D10 / SS', type: 'comm', desc: 'Digital Pin 10; SPI Slave Select (SS) / PWM output.' },
            { num: 12, name: 'D11 / MOSI', type: 'comm', desc: 'Digital Pin 11; SPI Master Out Slave In (MOSI) / PWM output.' },
            { num: 13, name: 'D12 / MISO', type: 'comm', desc: 'Digital Pin 12; SPI Master In Slave Out (MISO).' },
            { num: 14, name: 'D13 / SCK', type: 'comm', desc: 'Digital Pin 13; SPI Serial Clock (SCK). Governs SPI clock pacing, drives on-board L-LED.' },
            { num: 15, name: 'GND', type: 'gnd', desc: 'Ground Reference Pin. Low potential electrical boundary.' },
            { num: 16, name: 'AREF', type: 'analog', desc: 'Analog Voltage Reference. External voltage boundary for ADC computations.' },
            { num: 17, name: 'SDA', type: 'comm', desc: 'I2C Serial Data line. Inter-Integrated Circuit data bus.' },
            { num: 18, name: 'SCL', type: 'comm', desc: 'I2C Serial Clock line. Inter-Integrated Circuit clock synchronization line.' },
            { num: 19, name: 'RESET', type: 'gnd', desc: 'Active-Low Reset Trigger. Bring low to reset the onboard microcontroller.' },
            { num: 20, name: '3.3V', type: 'power', desc: '3.3 Volt DC power rail generated by on-board LDO regulator. Max current: 150mA.' },
            { num: 21, name: '5V', type: 'power', desc: '5 Volt regulated DC power output. Serves as primary voltage source for low power sensors.' },
            { num: 22, name: 'Vin', type: 'power', desc: 'Input Voltage Pin. Supplies raw DC voltage to the on-board voltage regulators when powered by an external source.' },
            { num: 23, name: 'A0', type: 'analog', desc: 'Analog Input Channel 0. Fed to internal 10-bit ADC converter.' },
            { num: 24, name: 'A1', type: 'analog', desc: 'Analog Input Channel 1.' },
            { num: 25, name: 'A2', type: 'analog', desc: 'Analog Input Channel 2.' },
            { num: 26, name: 'A3', type: 'analog', desc: 'Analog Input Channel 3.' },
            { num: 27, name: 'A4 / SDA', type: 'comm', desc: 'Analog Input 4 / I2C Data interface.' },
            { num: 28, name: 'A5 / SCL', type: 'comm', desc: 'Analog Input 5 / I2C Clock interface.' }
        ],
        datasheet: {
            title: 'Arduino Uno / ATmega328P technical characteristics',
            description: 'ATmega328P features high performance, low-power 8-bit AVR RISC architecture combining 32KB ISP Flash, 23 programmable I/O lines, and 10-bit Analog-to-Digital Converter.',
            electrical: [
                { parameter: 'VCC Supply Voltage', min: '1.8V', typ: '5.0V', max: '5.5V' },
                { parameter: 'DC Current per I/O Pin', min: '—', typ: '20.0 mA', max: '40.0 mA' },
                { parameter: 'Active Mode Current (8MHz)', min: '—', typ: '5.2 mA', max: '9.0 mA' },
                { parameter: 'Power-down sleep current', min: '—', typ: '0.1 uA', max: '2.0 uA' }
            ]
        }
    },
    
    esp32: {
        id: 'esp32',
        name: 'ESP32 NodeMCU',
        category: 'mcu',
        tag: 'Microcontroller',
        description: 'Powerful 32-bit Wi-Fi + Bluetooth System-on-Chip (SoC) dual-core module. Features integrated RF circuitry, operating at up to 240 MHz. Renders outstanding computational density for IoT nodes.',
        specs: {
            'Processor': 'Tensilica Xtensa Dual-Core 32-bit LX6',
            'Clock Frequency': 'Up to 240 MHz',
            'Wireless Connectivity': 'Wi-Fi 820.11 b/g/n & Bluetooth v4.2 BR/EDR and BLE',
            'SRAM': '520 KB',
            'External Flash': '4 MB',
            'Operating Voltage': '3.3V',
            'GPIO Pins': '30 (fully configurable with ADC, DAC, capacitive touch, SPI, I2C, UART)',
            'Integrated Sensors': 'Hall effect sensor, internal temperature sensor'
        },
        customizer: [
            { name: 'Solder Shielding', type: 'select', default: 'Metal Shaded', options: ['Metal Shaded', 'Clear Mesh', 'Black Matte'] },
            { name: 'Mounting Holes', type: 'select', default: 'With Screws', options: ['With Screws', 'PCB Only'] }
        ],
        pins: [
            { num: 1, name: '3.3V', type: 'power', desc: 'Primary 3.3V DC power input/output rail connected directly to onboard LDO regulator.' },
            { num: 2, name: 'GND', type: 'gnd', desc: 'Common electrical ground reference.' },
            { num: 3, name: 'GPIO36 / SENSOR_VP', type: 'analog', desc: 'General Purpose Input Only. Mapped to internal ADC1, low-noise pre-amplifier inputs.' },
            { num: 4, name: 'GPIO39 / SENSOR_VN', type: 'analog', desc: 'General Purpose Input Only. Mapped to ADC1 negative terminal.' },
            { num: 5, name: 'GPIO34', type: 'analog', desc: 'General Purpose Input Only. Useful for ADC input channels.' },
            { num: 6, name: 'GPIO35', type: 'analog', desc: 'General Purpose Input Only. Direct analog read input.' },
            { num: 7, name: 'GPIO32', type: 'digital', desc: 'General Purpose I/O. Supports ADC2 channel, capacitive touch sensor, 32.768kHz crystal oscillator.' },
            { num: 8, name: 'GPIO33', type: 'digital', desc: 'General Purpose I/O. Mapped to touch sensor, crystal connections.' },
            { num: 9, name: 'GPIO25 / DAC1', type: 'analog', desc: 'General Purpose I/O with Digital-to-Analog Converter (DAC 1). Outputs authentic analog voltages.' },
            { num: 10, name: 'GPIO26 / DAC2', type: 'analog', desc: 'General Purpose I/O with DAC 2.' },
            { num: 11, name: 'GPIO27', type: 'digital', desc: 'General Purpose I/O. Supports SPI, I2C, UART bus allocation.' },
            { num: 12, name: 'GPIO14 / HSPI_CLK', type: 'comm', desc: 'GPIO 14. Integrated Hardware SPI Clock (CLK).' },
            { num: 13, name: 'GPIO12 / HSPI_MISO', type: 'comm', desc: 'GPIO 12. Hardware SPI MISO interface.' },
            { num: 14, name: 'GPIO13 / HSPI_MOSI', type: 'comm', desc: 'GPIO 13. Hardware SPI MOSI interface.' },
            { num: 15, name: 'GND', type: 'gnd', desc: 'Common electrical ground boundary.' },
            { num: 16, name: 'VIN', type: 'power', desc: 'External USB/DC positive input voltage source. Input boundary: 5V regulated or 5V-12V unregulated.' },
            { num: 17, name: 'GPIO23 / VSPI_MOSI', type: 'comm', desc: 'GPIO 23. Secondary Hardware SPI Master Out Slave In interface.' },
            { num: 18, name: 'GPIO22 / I2C_SCL', type: 'comm', desc: 'GPIO 22. Default hardware I2C Serial Clock (SCL) line.' },
            { num: 19, name: 'GPIO1 / TXD0', type: 'comm', desc: 'Hardware Serial TXD0 pin. Used for primary UART debug printing.' },
            { num: 20, name: 'GPIO3 / RXD0', type: 'comm', desc: 'Hardware Serial RXD0 pin. Primary UART flashing receiver.' },
            { num: 21, name: 'GPIO21 / I2C_SDA', type: 'comm', desc: 'GPIO 21. Default hardware I2C Serial Data (SDA) line.' },
            { num: 22, name: 'GPIO19 / VSPI_MISO', type: 'comm', desc: 'GPIO 19. Hardware SPI Master In Slave Out line.' },
            { num: 23, name: 'GPIO18 / VSPI_SCK', type: 'comm', desc: 'GPIO 18. Hardware SPI Serial Clock line.' },
            { num: 24, name: 'GPIO5 / VSPI_SS', type: 'comm', desc: 'GPIO 5. Hardware SPI Slave Select line.' },
            { num: 25, name: 'GPIO17', type: 'digital', desc: 'General digital pin, commonly mapped to UART2 TX.' },
            { num: 26, name: 'GPIO16', type: 'digital', desc: 'General digital pin, commonly mapped to UART2 RX.' },
            { num: 27, name: 'GPIO4', type: 'digital', desc: 'General I/O pin. Features capacitive touch sensor.' },
            { num: 28, name: 'GPIO2 / STATUS_LED', type: 'pwm', desc: 'General I/O pin. Wired to onboard blue status LED. Supports PWM.' },
            { num: 29, name: 'GPIO15', type: 'digital', desc: 'General digital pin.' },
            { num: 30, name: 'EN / RST', type: 'gnd', desc: 'Enable / Reset Active-High pin. Pulled high. Force to Ground to restart chip.' }
        ],
        datasheet: {
            title: 'ESP32 Technical Specification Sheet',
            description: 'ESP32 combines Wi-Fi (802.11b/g/n) and Bluetooth (v4.2 BR/EDR/BLE) RF cores with an Xtensa dual-core LX6 CPU, targeting low power wireless embedded processing.',
            electrical: [
                { parameter: 'VDD Operating Voltage', min: '2.3V', typ: '3.3V', max: '3.6V' },
                { parameter: 'Wi-Fi Transmit Power Current', min: '—', typ: '240 mA', max: '320 mA' },
                { parameter: 'Deep Sleep Mode Current', min: '—', typ: '10 uA', max: '15 uA' },
                { parameter: 'I/O Pin Max Source Current', min: '—', typ: '12 mA', max: '40 mA' }
            ]
        }
    },
    
    ne555: {
        id: 'ne555',
        name: 'NE555 Precision Timer IC',
        category: 'ic',
        tag: 'Integrated Circuit',
        description: 'Highly stable device for generating accurate time delays or oscillation. Operating modes cover Astable (multivibrator clock) and Monostable (one-shot pulse), configurable by external passive elements.',
        specs: {
            'Supply Voltage Range': '4.5V to 16V',
            'Max Timing Frequency': '> 500 kHz',
            'Timing Range': 'Microseconds to hours',
            'Max Output Sink/Source': '200 mA',
            'Temperature Stability': '0.005% per °C',
            'Power Consumption': 'Typical 3 mA at 5V'
        },
        customizer: [
            { name: 'Package Model', type: 'select', default: 'DIP-8', options: ['DIP-8', 'SOIC-8'] },
            { name: 'Package Color', type: 'color', default: '#121212', options: ['#121212', '#2C3E50', '#2E4053'] }
        ],
        pins: [
            { num: 1, name: 'GND (Pin 1)', type: 'gnd', desc: 'Ground Reference. Connected to low potential circuit boundary.' },
            { num: 2, name: 'TRIG (Pin 2)', type: 'analog', desc: 'Trigger Pin. When voltage drops below 1/3 VCC, output (OUT) goes High and timing cycle starts.' },
            { num: 3, name: 'OUT (Pin 3)', type: 'digital', desc: 'Timer Output. Drives up to 200mA sink or source. Pin transitions between 0V and VCC-1.5V.' },
            { num: 4, name: 'RESET (Pin 4)', type: 'gnd', desc: 'Active-Low Reset input. Tie to VCC if not used. Pull below 0.4V to force OUT low.' },
            { num: 5, name: 'CONT (Pin 5)', type: 'analog', desc: 'Control Voltage. Accesses internal 2/3 VCC resistive divider network. Connects a 10nF capacitor to ground to suppress electrical noise.' },
            { num: 6, name: 'THRES (Pin 6)', type: 'analog', desc: 'Threshold input. Compares external timing capacitor voltage to internal reference (2/3 VCC). When exceeded, OUT drops Low.' },
            { num: 7, name: 'DISCH (Pin 7)', type: 'analog', desc: 'Discharge Output. Open collector transistor output synced with OUT. Discharges timing capacitor when OUT is Low.' },
            { num: 8, name: 'VCC (Pin 8)', type: 'power', desc: 'Positive Supply Voltage. Connects to DC voltage source between 4.5V and 16V.' }
        ],
        datasheet: {
            title: 'NE555 General Purpose Precision Timer',
            description: 'NE555 represents standard timing circuitry providing highly stable astable or monostable operational outputs using basic external resistor-capacitor sizing matrices.',
            electrical: [
                { parameter: 'VCC Supply Voltage Range', min: '4.5V', typ: '15.0V', max: '16.0V' },
                { parameter: 'Supply Current (VCC=5V, Low output)', min: '—', typ: '3.0 mA', max: '6.0 mA' },
                { parameter: 'Timing Error (Astable mode)', min: '—', typ: '1.5 %', max: '5.0 %' },
                { parameter: 'Output Voltage Low (Isink = 8mA)', min: '—', typ: '0.1V', max: '0.25V' }
            ]
        }
    },
    
    resistor: {
        id: 'resistor',
        name: 'Carbon Film Resistor',
        category: 'passive',
        tag: 'Axial Passive Component',
        description: 'Through-hole carbon film axial resistor. Restricts current flow in electrical paths according to Ohm\'s Law (V = IR). Value configurable via standard color rings code.',
        specs: {
            'Resistance Range': '10 Ω to 1 MΩ',
            'Standard Tolerances': '5% (Gold band)',
            'Power Rating': '0.25 W (1/4 Watt)',
            'Max Operating Voltage': '250V',
            'Temperature Coefficient': '-150 to -350 ppm/°C'
        },
        customizer: [
            { name: 'Resistance', type: 'select', default: '1k Ω', options: ['100 Ω', '220 Ω', '1k Ω', '10k Ω', '100k Ω'] },
            { name: 'Lead Length (mm)', type: 'range', min: 10, max: 30, default: 20 }
        ],
        pins: [
            { num: 1, name: 'Lead A', type: 'analog', desc: 'Polarity-independent electrical lead terminal.' },
            { num: 2, name: 'Lead B', type: 'analog', desc: 'Polarity-independent electrical lead terminal.' }
        ],
        datasheet: {
            title: 'Standard Carbon Axial Resistor Series',
            description: 'CFR carbon film resistors utilize vacuum-deposition techniques on premium ceramic core substrates to ensure robust stability and reliable thermal resistance limits.',
            electrical: [
                { parameter: 'Rated Wattage Power (70°C)', min: '—', typ: '0.25 W', max: '0.25 W' },
                { parameter: 'Max Insulation Voltage', min: '—', typ: '—', max: '500V' },
                { parameter: 'Dielectric Withstanding Voltage', min: '—', typ: '—', max: '350V' },
                { parameter: 'Resistance Temperature Slope', min: '—', typ: '-250ppm', max: '—' }
            ]
        }
    },
    
    capacitor: {
        id: 'capacitor',
        name: 'Electrolytic Capacitor',
        category: 'passive',
        tag: 'Radial Polarized Passive',
        description: 'Polarized cylindrical electrolytic capacitor. Stores electrostatic energy in an electric field. Polarized leads (anode must maintain higher potential than cathode). Renders crucial filter dampening.',
        specs: {
            'Capacitance Range': '1 uF to 1000 uF',
            'Voltage Rating Limits': '16V to 50V',
            'Standard Tolerances': '20%',
            'Max Core Temp limit': '105°C',
            'Equivalent Series Resistance (ESR)': 'Typical 1.2 Ω at 100kHz'
        },
        customizer: [
            { name: 'Capacitance', type: 'select', default: '10uF', options: ['1uF', '10uF', '100uF', '470uF'] },
            { name: 'Rated Voltage', type: 'select', default: '25V', options: ['16V', '25V', '50V'] }
        ],
        pins: [
            { num: 1, name: 'Anode (+)', type: 'analog', desc: 'Positive polarized terminal lead. Must operate at equal or greater potential than Cathode.' },
            { num: 2, name: 'Cathode (-)', type: 'gnd', desc: 'Negative polarized terminal lead. Marked by clear grey stripe printed on packaging.' }
        ],
        datasheet: {
            title: 'Radial Aluminum Electrolytic Capacitor Specs',
            description: 'ECA series radial capacitors represent extremely reliable filtering components featuring low impedance characteristics, high ripple current tolerances, and high thermal boundaries.',
            electrical: [
                { parameter: 'Capacitance Standard Tolerance', min: '-20%', typ: '—', max: '+20%' },
                { parameter: 'Surge DC Voltage Rating', min: '—', typ: '—', max: '32.0V' },
                { parameter: 'Leakage Current (2 minutes)', min: '—', typ: '3.0 uA', max: '10.0 uA' },
                { parameter: 'Ripple Current Rating (120Hz)', min: '—', typ: '85.0 mA', max: '190.0 mA' }
            ]
        }
    }
};

// Export to Global Window Namespace
window.ComponentDatabase = ComponentDatabase;
